import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { GroqService } from '../../../services/groq.service';
import { User } from '../../user/model';
import { GenerateWorkoutDto } from '../ai-coach.dto';
import { Program, ProgramExercise, UserProgram } from '../../program/model';
import {
  Exercise,
  MuscleGroup,
  Equipment,
  Difficulty,
} from '../../exercise/model';
import { ILike } from 'typeorm';

@Injectable()
export class GenerateWorkoutService {
  constructor(
    @InjectRepository(User)
    private userRepository: Repository<User>,
    @InjectRepository(Program)
    private programRepository: Repository<Program>,
    @InjectRepository(ProgramExercise)
    private programExerciseRepository: Repository<ProgramExercise>,
    @InjectRepository(UserProgram)
    private userProgramRepository: Repository<UserProgram>,
    @InjectRepository(Exercise)
    private exerciseRepository: Repository<Exercise>,
    private groqService: GroqService,
  ) {}

  async execute(
    dto: GenerateWorkoutDto,
    userId: string,
  ): Promise<{ workout: string; programId: string; structured: any }> {
    const user = await this.userRepository.findOne({ where: { id: userId } });

    const systemPrompt = `You are an expert fitness coach.
Create detailed, safe, and effective workout plans.
You MUST provide your response in two parts:
1. A human-friendly explanation of the plan.
2. A structured JSON representation of the plan at the end of your response, enclosed in <json></json> tags.

JSON structure:
{
  "name": "string (program name)",
  "description": "string",
  "duration": "string (e.g. '8 weeks')",
  "schedule": "string (e.g. '4 days / week')",
  "days": [
    {
      "dayDescription": "string (e.g. 'Monday - Upper Body')",
      "exercises": [
        {
          "name": "string",
          "sets": number,
          "reps": number,
          "restSeconds": number,
          "notes": "string",
          "muscleGroups": "one of: ${Object.values(MuscleGroup).join(', ')}",
          "equipmentType": "one of: ${Object.values(Equipment).join(', ')}",
          "difficultyLevel": "one of: ${Object.values(Difficulty).join(', ')}"
        }
      ]
    }
  ]
}`;

    const prompt = `Create a workout plan for a user with:
Level: ${user?.experienceLevel || 'intermediate'}
Goal: ${dto.goal}
Days/week: ${dto.daysPerWeek || 4}
Duration: ${dto.sessionDurationMinutes || 60}m
Equipment: ${dto.equipment || 'Full gym'}
Focus: ${dto.focusAreas || 'Balanced'}
Limitations: ${dto.limitations || 'None'}`;

    const response = await this.groqService.generateCompletion(
      prompt,
      systemPrompt,
    );

    // Extract human-friendly parts and JSON
    const jsonMatch = response.match(/<json>([\s\S]*?)<\/json>/);
    const workoutPlan = response.replace(/<json>[\s\S]*?<\/json>/, '').trim();
    let structuredData: any = null;

    if (jsonMatch) {
      try {
        structuredData = JSON.parse(jsonMatch[1].trim());
      } catch (e) {
        console.error('Failed to parse AI JSON response:', e);
      }
    }

    let programIdResult = '';
    if (structuredData) {
      // Create the program in the database
      const program = await this.programRepository.save(
        this.programRepository.create({
          name: structuredData.name || `AI Generated ${dto.goal}`,
          description:
            structuredData.description || 'Custom plan generated by AI Coach',
          duration: structuredData.duration || 'Custom',
          schedule: structuredData.schedule || 'Custom',
          isAvailable: true,
        }),
      );
      programIdResult = program.id;

      // Enroll user in the program
      await this.userProgramRepository.save(
        this.userProgramRepository.create({
          userId,
          programId: program.id,
          isActive: true,
        }),
      );

      // Add exercises
      for (const day of structuredData.days || []) {
        let orderIndex = 1;
        for (const exerciseData of day.exercises || []) {
          // Find or create exercise
          let exercise = await this.exerciseRepository.findOne({
            where: { name: ILike(exerciseData.name) },
          });

          if (!exercise) {
            exercise = await this.exerciseRepository.save(
              this.exerciseRepository.create({
                name: exerciseData.name,
                muscleGroups:
                  exerciseData.muscleGroups || MuscleGroup.FULL_BODY,
                equipmentType: exerciseData.equipmentType || Equipment.OTHER,
                difficultyLevel:
                  exerciseData.difficultyLevel || Difficulty.INTERMEDIATE,
              }),
            );
          }

          // Link to program
          await this.programExerciseRepository.save(
            this.programExerciseRepository.create({
              programId: program.id,
              exerciseId: exercise.id,
              daysOfTheWeek: day.dayDescription,
              order: orderIndex++,
              targetSets: exerciseData.sets || 3,
              targetReps: exerciseData.reps || 10,
              restTime: exerciseData.restSeconds || 60,
              notes: exerciseData.notes,
            }),
          );
        }
      }
    }

    return {
      workout: workoutPlan,
      programId: programIdResult,
      structured: {
        goal: dto.goal,
        daysPerWeek: dto.daysPerWeek || 4,
        sessionDuration: dto.sessionDurationMinutes || 60,
        generatedAt: new Date().toISOString(),
      },
    };
  }
}
